#服务端端口
server:
  port: 9091
#日志
log:
  path: ./log

#配置服务端口URL路径提供客户端使用
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:@project.version@
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: true
    fetch-registry: true